#!/usr/bin/ruby

require "./deck"
require "./game"
require "./player"

deck = getDeck()
turn = "you"
topCard = getRandomCard(deck)

botHand = getRandomHand(deck)
playerHand = getRandomHand(deck)

while botHand.length != 0 && playerHand.length != 0 do
  if turn === "you"
    newTopCard = playerGoes(deck, playerHand, topCard)
    playerHand.delete_if{|card| card[:id] === newTopCard[:id]}
    topCard = newTopCard
    turn = "comp"
  end
  if turn === "comp" 
    # bot goes
    botHand.pop
  end
end

if botHand.length === 0
 puts "Sorry, computer wins!"
else
 puts "Congratulations, you win!"
end

